'use client';
import {useEffect,useState} from 'react';
import {companies} from './demo';
import {paletteHexes} from './brand';
export type Organization={id:string;name:string;sector:string;status:string;description:string;audience:string;products:string;services:string;pricing:string;billing:string;profit:string;ownership:string;values:string;guidance:string;logo:string;color?:string};
export const organizationKey='none-organizations-v1';
export const initialOrganizations:Organization[]=companies.map(c=>({id:c.id,name:c.name,sector:c.sector,status:c.type==='implantacao'?'Em implantação':'Em operação',description:'',audience:'',products:'',services:'',pricing:'',billing:'',profit:'',ownership:'',values:'',guidance:'',logo:''}));
const fields=['id','name','sector','status','description','audience','products','services','pricing','billing','profit','ownership','values','guidance','logo'] as const;
export function readOrganizations():Organization[]{if(typeof window==='undefined')return initialOrganizations;const raw=localStorage.getItem(organizationKey);if(!raw)return initialOrganizations;const v=JSON.parse(raw);if(v.version!==1||!Array.isArray(v.items)||!v.items.every((x:Organization)=>x&&fields.every(k=>typeof x[k]==='string'&&x[k].length<=(k==='logo'?550000:10000))&&/^(integral|mcl|reurb|ct|bergamota|vidas|org-[a-f0-9-]{36})$/.test(x.id)&&x.name.trim()&&(!x.logo||/^data:image\/(png|jpeg|webp);base64,/.test(x.logo))&&(x.color===undefined||paletteHexes.includes(x.color)))||new Set(v.items.map((x:Organization)=>x.id)).size!==v.items.length)throw Error('invalid');return v.items;}
export function organizationContext(id:string){try{const orgs=readOrganizations();const selected=id==='all'?orgs:orgs.filter(o=>o.id===id);return 'none é a holding de investimentos. As organizações abaixo são investimentos do portfólio; participação e repasses dependem dos dados cadastrados.\n'+selected.map(o=>[o.name,...(['description','sector','status','audience','products','services','pricing','billing','profit','ownership','values','guidance'] as const).filter(k=>o[k]).map(k=>labels[k]+': '+o[k])].join('\n')).join('\n\n');}catch{return 'Contexto cadastral indisponível; não presumir informações.';}}
export const labels:Record<string,string>={name:'Nome da organização',sector:'Setor de atuação',status:'Estágio do investimento',description:'Sobre a organização',audience:'Clientes e público-alvo',products:'Linhas de produtos',services:'Serviços oferecidos',pricing:'Preços e condições comerciais',billing:'Formas de cobrança e recebimento',profit:'Distribuição de lucros e repasses à none',ownership:'Participação da none e relação societária',values:'Valores da marca e diferenciais',guidance:'Orientações e limites para os agentes'};
export function useOrganizations(){const [items,setItems]=useState(initialOrganizations);const [ready,setReady]=useState(false);const [error,setError]=useState('');useEffect(()=>{const refresh=()=>{try{setItems(readOrganizations());setReady(true);setError('');}catch{setReady(false);setError('Não foi possível ler o cadastro salvo. Os dados foram preservados.');}};refresh();window.addEventListener('none-organizations',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('none-organizations',refresh);window.removeEventListener('storage',refresh);};},[]);function save(org:Organization){if(!ready)throw Error('Cadastro indisponível.');const current=readOrganizations();const next=current.some(o=>o.id===org.id)?current.map(o=>o.id===org.id?org:o):[...current,org];localStorage.setItem(organizationKey,JSON.stringify({version:1,items:next}));setItems(next);window.dispatchEvent(new Event('none-organizations'));}return {items,ready,error,save};}
