import type {AgentProfile,Tone} from './agent-profiles';

export const socialProfile:AgentProfile={
 id:'social',name:'Redes Sociais',role:'Planeja conteúdo e prepara conversas no Instagram e LinkedIn.',
 mission:'Administrar a presença pessoal e das empresas no Instagram e LinkedIn, preparando publicações e respostas alinhadas à voz de cada perfil para revisão.',
 scopes:['personal','integral','mcl','reurb','ct','bergamota','vidas'],
 responsibilities:['Planejar pautas e calendário editorial por perfil','Preparar legendas, carrosséis e roteiros para Instagram','Redigir publicações profissionais para LinkedIn','Preparar respostas a comentários e mensagens privadas','Encaminhar oportunidades ao Comercial e reclamações ao atendimento humano','Acompanhar indicadores quando houver dados oficiais conectados'],
 sources:['Instagram — conta a conectar','LinkedIn — perfil ou página a conectar','Diretrizes de marca e público','Conteúdos e imagens autorizados'],
 limits:['Nenhuma conta está conectada neste protótipo','Não publicar, agendar ou responder pessoas nesta etapa','Não inventar depoimentos, resultados, preços ou métricas','Não divulgar informações internas, dados pessoais ou imagens sem autorização','Encaminhar reclamações, assuntos sensíveis e compromissos comerciais para revisão humana'],
 tasks:[
  {id:'social_instagram',name:'Post para Instagram',hint:'Ex.: carrossel fictício sobre organização de projetos. Informe público, objetivo e formato.'},
  {id:'social_linkedin',name:'Post para LinkedIn',hint:'Ex.: reflexão profissional sobre gestão. Informe público, objetivo e fatos que podem ser usados.'},
  {id:'social_calendar',name:'Planejamento editorial',hint:'Ex.: pautas de uma semana para Instagram e LinkedIn, com foco institucional.'},
  {id:'social_comment_ig',name:'Responder comentário · Instagram',hint:'Ex.: comentário fictício: “Como posso saber mais sobre o serviço?”'},
  {id:'social_comment_li',name:'Responder comentário · LinkedIn',hint:'Ex.: comentário fictício sobre uma publicação profissional.'},
  {id:'social_dm_ig',name:'Responder mensagem · Instagram',hint:'Ex.: mensagem fictícia pedindo informações. Não informe dados pessoais reais.'},
  {id:'social_dm_li',name:'Responder mensagem · LinkedIn',hint:'Ex.: contato fictício propondo uma conversa profissional.'},
 ],
 instructions:'Separe cada perfil e empresa. Adapte o conteúdo ao Instagram ou LinkedIn, com objetivo, público e chamada para ação. Use apenas fatos confirmados. Prepare rascunhos para aprovação. Em respostas, seja cordial, não exponha dados em comentários públicos e encaminhe dúvidas comerciais, reclamações e assuntos sensíveis. Não finja ter consultado contas ou métricas.'
};

export function simulateSocial(task:string,name:string,tone:Tone,brief:string,implantation:boolean){
 const hello=tone==='formal'?'Olá, agradecemos seu contato.':tone==='direto'?'Olá! Obrigado pelo contato.':'Olá! Que bom receber sua mensagem.';
 const review='\n\nREVISÃO ANTES DE USAR\nConferir perfil, destinatário ou público, fatos, direitos de imagem e tom. O pedido acima deve orientar sua edição: este roteiro local não interpreta o briefing com IA. Nenhum conteúdo foi publicado, agendado ou enviado.';
 if(task==='social_calendar')return `PLANEJAMENTO EDITORIAL · ${name}\nPeríodo e datas: a definir\n\nPauta 1 · Instagram · Carrossel\nObjetivo: apresentar uma ideia útil.\nEstrutura: pergunta inicial, três pontos e convite à conversa.\n\nPauta 2 · LinkedIn · Texto\nObjetivo: compartilhar uma reflexão profissional baseada em experiência confirmada.\nEstrutura: contexto, aprendizado e pergunta ao público.\n\nPauta 3 · Instagram · Stories\nObjetivo: ouvir dúvidas do público com uma pergunta simples.\n\nPauta 4 · LinkedIn · Texto ou documento\nObjetivo: aprofundar uma das dúvidas recebidas, sem expor quem perguntou.\n\nPARA CADA PAUTA\nDefinir responsável, material autorizado, data e aprovação. ${implantation?'Como este projeto está em implantação, não anunciar abertura, ofertas ou disponibilidade sem confirmação.':''}\n\nIndicadores futuros: alcance, interações e conversas qualificadas, somente após conexão com fontes oficiais. Sem métricas reais disponíveis.`+review;
 if(task.includes('comment')||task.includes('dm')){
  const publicReply=task.includes('comment');const channel=task.endsWith('_ig')?'Instagram':'LinkedIn';
  const sensitive=/reclama|insatisfeit|processo|ameaça|vazamento|reembolso|urgente|fraude/i.test(brief);
  return `RESPOSTA PARA REVISÃO · ${channel}\nTipo: ${publicReply?'comentário público':'mensagem privada'}\nPerfil: ${name}\n\nRASCUNHO\n${sensitive?`Obrigado por nos avisar. Queremos entender melhor o que aconteceu e encaminhar o assunto à pessoa responsável. ${publicReply?'Por favor, evite compartilhar informações pessoais neste comentário. Podemos continuar em um canal privado oficial.':'Pode resumir o ocorrido, sem enviar documentos ou dados sensíveis por aqui?'}`:`${hello} ${publicReply?'Obrigado por participar da conversa. Qual ponto você gostaria que aprofundássemos?':'Pode nos contar brevemente o assunto e o que você gostaria de entender melhor? Assim, podemos preparar o próximo passo com a pessoa responsável.'}`}\n\nENCAMINHAMENTO\n${sensitive?'Revisão humana prioritária. Não prometer solução, prazo ou reembolso.':'Se houver interesse comercial, encaminhar ao Comercial após confirmar o contexto. Não prometer preços ou condições.'}\n\nTriagem demonstrativa por palavras-chave. A mensagem original e o histórico não foram consultados na rede social.`+review;
 }
 if(task==='social_instagram')return `POST PARA INSTAGRAM · ${name}\nFormato sugerido: carrossel, sujeito à revisão\nPúblico e objetivo específicos: confirmar a partir do pedido\n\nROTEIRO VISUAL\nCapa: Uma boa ideia começa com uma pergunta.\nSlide 2: O que queremos melhorar?\nSlide 3: O que já sabemos e o que falta validar?\nSlide 4: Qual é o próximo passo possível?\nSlide 5: Convite para compartilhar uma dúvida.\n\nLEGENDA DE EXEMPLO\n${tone==='direto'?'Pergunte. Organize. Experimente.':'Antes de dar o próximo passo, vale organizar as perguntas certas.'} ${implantation?'Estamos estruturando ideias para um projeto em implantação. As novidades serão compartilhadas quando estiverem confirmadas.':'Clareza de objetivo ajuda a transformar ideias em próximos passos.'}\n\nQue pergunta você colocaria nessa lista?\n\nPRODUÇÃO\nAdaptar a pauta ao briefing, selecionar imagens autorizadas, escrever texto alternativo e revisar a legibilidade. Hashtags devem ser escolhidas após definir o tema. Não há imagem gerada nem horário agendado.`+review;
 return `POST PARA LINKEDIN · ${name}\nFormato: texto profissional\nObjetivo específico e público: a confirmar\n\nRASCUNHO\nUma ideia ganha força quando fica claro qual problema ela pretende resolver.\n\nAntes de avançar, três perguntas ajudam a organizar a conversa:\n• O que sabemos com segurança?\n• O que ainda precisa ser validado?\n• Qual pequeno passo pode gerar aprendizado?\n\n${implantation?'Em um projeto em implantação, esse cuidado também orienta a preparação das próximas etapas.':'Esse roteiro pode apoiar conversas sobre projetos, processos e prioridades.'}\n\nComo você organiza essas perguntas no seu trabalho?\n\nPERSONALIZAÇÃO\nSubstituir o exemplo por fatos e experiências autorizados. Não atribuir resultados, cargos ou experiências pessoais que não tenham sido fornecidos.`+review;
}
