import type {Company,Decision,DemoState} from './domain';
export const companies:Company[]=[
 {id:'integral',name:'Integral Soluções em Engenharia',short:'Integral',initials:'IN',sector:'Engenharia',type:'operacao',color:'teal',description:'Visão executiva dos projetos, propostas e prioridades da operação de engenharia.',nextStep:'Complete o cadastro e conecte as fontes de dados.',metrics:[]},
 {id:'mcl',name:'Minha Casa Legal',short:'Minha Casa Legal',initials:'MC',sector:'Regularização fundiária',type:'operacao',color:'blue',description:'Acompanhamento executivo de regularização, recebimentos e relacionamento com clientes.',nextStep:'Complete o cadastro e conecte as fontes de dados.',metrics:[]},
 {id:'reurb',name:'REURB.Software',short:'REURB.Software',initials:'RE',sector:'Tecnologia',type:'operacao',color:'violet',description:'Uma visão do relacionamento comercial, adoção da plataforma e próximos passos de produto.',nextStep:'Complete o cadastro e conecte as fontes de dados.',metrics:[]},
 {id:'ct',name:'CT Diego Silva',short:'CT Diego Silva',initials:'CT',sector:'Centro de treinamento',type:'operacao',color:'orange',description:'Empresa em sociedade. Estrutura preparada para futuros relatórios financeiros e de clientes.',nextStep:'Complete o cadastro e conecte as fontes de dados.',metrics:[]},
 {id:'bergamota',name:'Bergamota',short:'Bergamota',initials:'BE',sector:'Confeitaria · Investimento',type:'implantacao',color:'rose',description:'Investimento em uma confeitaria, em fase de implantação. Espaço reservado para acompanhar a evolução do negócio.',nextStep:'Complete o cadastro e conecte as fontes de dados.',metrics:[]},
 {id:'vidas',name:'Cartão Vidas',short:'Cartão Vidas',initials:'CV',sector:'Clube de vantagens · Investimento',type:'implantacao',color:'cyan',description:'Investimento em um clube de vantagens, em fase de implantação. Acompanhamento futuro de clientes, parceiros e resultados.',nextStep:'Complete o cadastro e conecte as fontes de dados.',metrics:[]},
];
export const connections=[{name:'Supabase',purpose:'Dados, autenticação e documentos',kind:'Base central'},{name:'Chatwoot',purpose:'Conversas e relacionamento',kind:'Atendimento'},{name:'Gmail',purpose:'E-mails e contexto de decisões',kind:'Comunicação'},{name:'Calendar',purpose:'Agenda e compromissos',kind:'Agenda'},{name:'ERPs / CRMs',purpose:'Indicadores dos sistemas existentes',kind:'Operação'},{name:'Redes sociais',purpose:'Contas a definir · Pautas e publicações para revisão',kind:'Comunicação'}];
export const initialState:DemoState={version:1,decisions:{},agentRuns:{},audit:[]};
export const decisions:Decision[]=[];
export function answerDemo():string{return 'A IA ainda não está conectada. O contexto acima foi consultado no cadastro local; não há análise financeira ou acesso a fontes externas.';}
