'use client';
import {useOrganizations,organizationContext} from '@/lib/organizations';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Instagram,Linkedin,CalendarDays,Check,CheckCheck,FileText,Headphones,Mail,MessageSquare,Play,Save,Settings2,ShieldCheck,Sparkles,Users,Wallet,Wrench} from 'lucide-react';
import {agentProfiles,defaultConfig,scopeName,simulateAgent,validWorkspace} from '@/lib/agents';
import type {AgentConfig,AgentDraft,AgentId,AgentProfile,AgentScope,AgentWorkspace,Tone} from '@/lib/agents';
import type {DemoState} from '@/lib/domain';

const icons={social:Instagram,executive:Sparkles,finance:Wallet,projects:Wrench,sales:Users,reception:Headphones,secretary:CalendarDays};
const key='none-agents-v1';
const initial:AgentWorkspace={version:1,configs:{},drafts:[]};
type AiState='checking'|'conectado'|'nao_configurado'|'erro';
const aiLabel:Record<AiState,string>={checking:'Verificando IA…',conectado:'IA conectada',nao_configurado:'IA não configurada',erro:'IA indisponível'};
function useAiState(){const [ai,setAi]=useState<AiState>('checking');const [model,setModel]=useState('');useEffect(()=>{let alive=true;fetch('/api/agentes').then(r=>r.ok?r.json():Promise.reject()).then((d:{state?:AiState;model?:string})=>{if(!alive)return;setAi(d.state==='conectado'||d.state==='nao_configurado'||d.state==='erro'?d.state:'erro');setModel(d.model??'');}).catch(()=>{if(alive)setAi('erro');});return()=>{alive=false;};},[]);return {ai,model};}
export function AgentHub({state,onRun}:{state:DemoState;onRun:(id:string)=>void}){
 const [workspace,setWorkspace]=useState<AgentWorkspace>(initial);const [loaded,setLoaded]=useState(false);const [warning,setWarning]=useState('');const [canSave,setCanSave]=useState(true);const [selected,setSelected]=useState<AgentId|null>(null);const {ai,model}=useAiState();
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const saved:unknown=JSON.parse(raw);if(validWorkspace(saved))setWorkspace(saved);else{setCanSave(false);setWarning('Não foi possível recuperar a configuração anterior. O salvamento foi suspenso para preservar os dados existentes.');}}}catch{setCanSave(false);setWarning('O armazenamento deste navegador não está disponível. Suas alterações durarão apenas nesta sessão.');}setLoaded(true);},[]);
 useEffect(()=>{if(!loaded||!canSave)return;try{localStorage.setItem(key,JSON.stringify(workspace));}catch{setWarning('Não foi possível salvar neste navegador. Mantenha esta página aberta para conservar suas alterações nesta sessão.');}},[workspace,loaded,canSave]);
 const profile=agentProfiles.find(a=>a.id===selected);
 function addDraft(draft:AgentDraft){setWorkspace(w=>({...w,drafts:[draft,...w.drafts].slice(0,30)}));onRun(draft.agentId);}
 return <>{warning?<p role="status" className="storage-warning">{warning}</p>:null}{profile?<AgentWorkspaceView key={profile.id} profile={profile} config={workspace.configs[profile.id]??defaultConfig(profile)} drafts={workspace.drafts.filter(d=>d.agentId===profile.id)} ai={ai} model={model} onBack={()=>setSelected(null)} onSave={config=>setWorkspace(w=>({...w,configs:{...w.configs,[profile.id]:config}}))} onDraft={addDraft} onEdit={draft=>setWorkspace(w=>({...w,drafts:w.drafts.map(d=>d.id===draft.id?draft:d)}))}/>:<>
  <div className="page-heading"><div><p className="eyebrow">SUA EQUIPE NONE</p><h1>Cada setor, um olhar dedicado.</h1><p>Configure o escopo de cada agente e peça rascunhos para revisar.</p></div><span className={`badge ${ai==='conectado'?'green':''}`}>{aiLabel[ai]}</span></div>
  <section className="agent-overview"><div><span className="ai-symbol"><Sparkles size={20}/></span><h2>Da entrada à revisão.</h2><p>Recepção, especialistas e rotina pessoal em um único espaço.</p></div><div className="agent-flow"><span>Recepcionar</span><i>→</i><span>Preparar</span><i>→</i><span>Você revisa</span><small>{ai==='conectado'?'Rascunhos gerados pela IA':'IA não conectada'} · Nenhuma mensagem, publicação ou convite é enviado.</small></div></section>
  <div className="agent-grid prepared-agents">{agentProfiles.map(a=>{const Icon=icons[a.id];const config=workspace.configs[a.id]??defaultConfig(a);const count=workspace.drafts.filter(d=>d.agentId===a.id).length;return <section className="panel agent-card" key={a.id}><div className="agent-card-top"><span className="agent-icon"><Icon size={24}/></span><span className="badge">{workspace.configs[a.id]?'Personalizado':'Perfil preparado'}</span></div><h2>Agente {a.name}</h2><p>{a.role}</p><div className="agent-deliveries">{a.tasks.map(t=><span key={t.id}>{t.name}</span>)}</div><div className="agent-scope"><small>CONTEXTO</small><span>{config.scopes.length} {config.scopes.length===1?'contexto selecionado':'contextos selecionados'}{config.scopes.includes('personal')?' · Inclui rotina pessoal':''}</span></div><div className="agent-last">{count?`${count} ${count===1?'rascunho':'rascunhos'} · `:''}{aiLabel[ai]}</div><button className="outline" onClick={()=>{setSelected(a.id);window.scrollTo({top:0,behavior:'instant'});}} disabled={!loaded} aria-label={`Abrir agente ${a.name}`}>Abrir agente<ArrowUpRight size={17}/></button></section>;})}</div>
  <div className="integration-note agent-limit-note"><ShieldCheck size={23}/><div><h3>{ai==='conectado'?'A IA prepara, você revisa.':'Conecte a IA para gerar rascunhos.'}</h3><p>{ai==='conectado'?`Os agentes usam ${model||'o Claude'} com o cadastro das empresas e, no Financeiro e no Executivo, os indicadores conectados. Nada é enviado, publicado ou agendado. Configurações e rascunhos ficam neste navegador.`:'Os agentes dependem da chave da IA configurada no servidor (ANTHROPIC_API_KEY). Veja o estado em Conexões.'}</p></div></div>
 </>}</>;
}

function AgentWorkspaceView({profile:p,config,drafts,ai,model,onBack,onSave,onDraft,onEdit}:{profile:AgentProfile;config:AgentConfig;drafts:AgentDraft[];ai:AiState;model:string;onBack:()=>void;onSave:(c:AgentConfig)=>void;onDraft:(d:AgentDraft)=>void;onEdit:(d:AgentDraft)=>void}){
 const portfolio=useOrganizations();
 const [tab,setTab]=useState<'work'|'config'|'mission'>('work');const [editing,setEditing]=useState<AgentConfig>(()=>({...config,scopes:[...config.scopes]}));const [scope,setScope]=useState<AgentScope>(config.scopes[0]);const [task,setTask]=useState(p.tasks[0].id);const [brief,setBrief]=useState('');const [running,setRunning]=useState(false);const [notice,setNotice]=useState('');const [selectedDraft,setSelectedDraft]=useState<string|null>(drafts[0]?.id??null);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const Icon=icons[p.id];const currentTask=p.tasks.find(t=>t.id===task)!;const unsaved=JSON.stringify(editing)!==JSON.stringify(config);const activeDraft=drafts.find(d=>d.id===selectedDraft);const effectiveScope=config.scopes.includes(scope)?scope:config.scopes[0];
 function save(){if(!editing.scopes.length){setNotice('Selecione pelo menos um contexto.');return;}onSave({...editing,scopes:[...editing.scopes]});setScope(editing.scopes[0]);setNotice('Configuração salva. A IA usará estas orientações nos próximos rascunhos.');}
 async function run(e:React.FormEvent){e.preventDefault();if(ai!=='conectado'||running||unsaved)return;const text=brief.trim();if(!text){setNotice('Descreva o pedido.');return;}
  setRunning(true);setNotice('');
  try{
   const res=await fetch('/api/agentes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentId:p.id,taskId:task,scope:effectiveScope,scopeName:scopeName(effectiveScope),scopeNames:config.scopes.map(scopeName),orgContext:effectiveScope==='personal'?'':organizationContext(effectiveScope),brief:text,config})});
   const data=await res.json().catch(()=>({})) as {text?:string;error?:string};
   if(!res.ok||!data.text){setNotice(data.error??'Não foi possível gerar o rascunho agora.');return;}
   const now=new Date().toISOString();const draft:AgentDraft={id:crypto.randomUUID(),agentId:p.id,taskId:task,scope:effectiveScope,brief:text,body:data.text.slice(0,50000),status:'draft',createdAt:now,updatedAt:now,config:{...config,scopes:[...config.scopes]},mode:'ai'};
   onDraft(draft);setSelectedDraft(draft.id);setNotice('Rascunho pronto para sua revisão.');
  }catch{setNotice('Sem conexão com o servidor. Tente novamente.');}
  finally{setRunning(false);}
 }
 return <div className="agent-workspace"><button className="text-button back-button" onClick={onBack}><ArrowLeft size={16}/>Todos os agentes</button><div className="agent-detail-heading"><span className="agent-icon"><Icon size={26}/></span><div><p className="eyebrow">AGENTE NONE</p><h1>{p.name}</h1><p>{p.role}</p></div><span className={`badge ${ai==='conectado'?'green':''}`}>{aiLabel[ai]}</span></div>
 <div className="agent-view-nav" aria-label="Áreas do agente">{([{id:'work',label:'Área de trabalho',icon:FileText},{id:'config',label:'Configuração',icon:Settings2},{id:'mission',label:'Funções e limites',icon:ShieldCheck}] as const).map(t=><button key={t.id} className={tab===t.id?'selected':''} aria-pressed={tab===t.id} onClick={()=>{setTab(t.id);setNotice('');}}><t.icon size={17}/>{t.label}</button>)}</div>
 {notice?<p key={notice} className="agent-feedback" role="status"><Check size={17}/>{notice}</p>:null}
 {tab==='work'?<><div className="agent-work-grid"><section className="panel agent-request"><h2>Preparar uma entrega</h2><p>{ai==='conectado'?'Descreva o pedido; a IA prepara um rascunho para você revisar.':'A geração de entregas depende da conexão com a IA.'}</p><form onSubmit={run}><label htmlFor="agent-task">O que você precisa?</label><select id="agent-task" value={task} onChange={e=>setTask(e.target.value)} disabled={running}>{p.tasks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><label htmlFor="agent-scope">Empresa ou contexto</label><select id="agent-scope" value={effectiveScope} onChange={e=>setScope(e.target.value as AgentScope)} disabled={running}>{config.scopes.map(s=><option key={s} value={s}>{scopeName(s)}</option>)}</select><label htmlFor="agent-brief">Pedido</label><textarea id="agent-brief" value={brief} onChange={e=>setBrief(e.target.value)} placeholder={currentTask.hint} maxLength={1500} required disabled={running}/><p className="agent-field-hint">{ai==='conectado'?`Usa as orientações salvas e o cadastro de ${scopeName(effectiveScope)}.`:ai==='checking'?'Verificando a conexão com a IA…':'IA não conectada. Verifique a chave da IA em Conexões.'}</p>{unsaved?<p className="agent-unsaved">Há alterações não salvas. Salve a configuração antes de continuar.</p>:null}<button className="primary" disabled={ai!=='conectado'||running||unsaved}><Play size={16}/>{running?'Preparando rascunho…':ai==='conectado'?'Gerar rascunho':aiLabel[ai]}</button></form><div className="agent-no-send"><ShieldCheck size={17}/><span>Preparar e revisar não envia nem executa nada.</span></div></section>
 <section className="panel agent-output">{activeDraft?<DraftEditor key={activeDraft.id} draft={activeDraft} profile={p} onChange={onEdit}/>:<div className="agent-output-empty"><Icon size={32}/><h2>O próximo passo começa aqui.</h2><p>Escolha uma entrega e descreva um pedido de exemplo. O rascunho aparecerá neste espaço para você revisar.</p>{p.id==='social'?<div className="secretary-channels"><span><Instagram size={17}/>Instagram</span><span><Linkedin size={17}/>LinkedIn</span><span><MessageSquare size={17}/>Posts e respostas</span></div>:null}{p.id==='secretary'?<div className="secretary-channels"><span><MessageSquare size={17}/>Redes sociais</span><span><Mail size={17}/>E-mails</span><span><CalendarDays size={17}/>Agenda</span></div>:null}</div>}</section></div>
 <section className="panel agent-draft-history"><div className="section-header"><h2>Entregas deste agente</h2><span className="badge">Últimos 30 rascunhos da equipe</span></div>{drafts.length?<div className="draft-list">{drafts.map(d=><button key={d.id} className={selectedDraft===d.id?'selected':''} onClick={()=>setSelectedDraft(d.id)}><FileText size={19}/><span><strong>{p.tasks.find(t=>t.id===d.taskId)?.name}</strong><small>{scopeName(d.scope)} · {new Date(d.createdAt).toLocaleString('pt-BR')}</small></span><span className={`badge ${d.status==='reviewed'?'green':''}`}>{d.status==='reviewed'?'Revisado':'Rascunho'}</span></button>)}</div>:<p className="history-empty">Nenhuma entrega ainda. Seus rascunhos ficarão salvos neste navegador.</p>}</section></>:null}
 {tab==='config'?<section className="panel agent-config"><div><h2>Como este agente deve trabalhar</h2><p>Defina os contextos permitidos e as orientações que a IA deve seguir.</p></div><fieldset><legend>Empresas e contextos</legend><div className="agent-scope-options">{Array.from(new Set([...p.scopes,...portfolio.items.map(o=>o.id)])).map(s=><label key={s}><input type="checkbox" checked={editing.scopes.includes(s)} onChange={e=>setEditing(c=>({...c,scopes:e.target.checked?[...c.scopes,s]:c.scopes.filter(x=>x!==s)}))}/><span>{scopeName(s)}</span></label>)}</div></fieldset><label className="field-label" htmlFor="agent-tone">Tom da comunicação</label><select id="agent-tone" value={editing.tone} onChange={e=>setEditing(c=>({...c,tone:e.target.value as Tone}))}><option value="cordial">Cordial e profissional</option><option value="direto">Direto e objetivo</option><option value="formal">Formal</option></select><label className="field-label" htmlFor="agent-instructions">Instruções do agente</label><textarea id="agent-instructions" maxLength={3000} value={editing.instructions} onChange={e=>setEditing(c=>({...c,instructions:e.target.value}))}/><p className="agent-field-hint">A IA segue estas instruções em cada rascunho. Os limites de atuação permanecem obrigatórios.</p><div className="config-footer"><button className="primary" onClick={save} disabled={!editing.scopes.length||!unsaved}><Save size={17}/>Salvar configuração</button><span>{unsaved?'Alterações não salvas':'Configuração atual'}</span></div></section>:null}
 {tab==='mission'?<div className="agent-mission-grid"><section className="panel mission-card"><h2>Missão</h2><p>{p.mission}</p><h3>Responsabilidades</h3><ul>{p.responsibilities.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></section><section className="panel mission-card"><h2>Limites de atuação</h2><ul>{p.limits.map(x=><li key={x}><ShieldCheck size={16}/>{x}</li>)}</ul><div className="agent-no-send"><ShieldCheck size={17}/><span>Marcar um rascunho como revisado registra apenas a sua revisão.</span></div></section><section className="panel mission-card sources-card"><h2>Fontes para a próxima etapa</h2><p>A IA usa o pedido e o cadastro da empresa{p.id==='finance'||p.id==='executive'?', além dos indicadores conectados':''}. As fontes abaixo ainda não estão ligadas ao agente.</p><div className="agent-source-list">{p.sources.map(x=><div key={x}><span>{x}</span><span className="badge">Não conectado</span></div>)}</div></section></div>:null}
 </div>;
}

function DraftEditor({draft,profile,onChange}:{draft:AgentDraft;profile:AgentProfile;onChange:(d:AgentDraft)=>void}){
 const [body,setBody]=useState(draft.body);const changed=body!==draft.body;const empty=!body.trim();
 function update(status:AgentDraft['status']){onChange({...draft,body,status,updatedAt:new Date().toISOString()});}
 return <><div className="agent-output-heading"><div><p className="eyebrow">{draft.mode==='ai'?'RASCUNHO DA IA':'ENTREGA DEMONSTRATIVA'}</p><h2>{profile.tasks.find(t=>t.id===draft.taskId)?.name}</h2></div><span className={`badge ${draft.status==='reviewed'&&!changed?'green':''}`}>{changed?'Edição não salva':draft.status==='reviewed'?'Revisado':'Rascunho'}</span></div><p className="agent-output-context">{scopeName(draft.scope)}</p><label className="sr-only" htmlFor="agent-draft-content">Conteúdo do rascunho</label><textarea id="agent-draft-content" value={body} maxLength={12000} onChange={e=>{const value=e.target.value;setBody(value);onChange({...draft,body:value,status:'draft',updatedAt:new Date().toISOString()});}}/><div className="draft-actions"><span className="agent-field-hint">Salvamento automático neste navegador</span><button className="primary" disabled={changed||empty||draft.status==='reviewed'} onClick={()=>update('reviewed')}><CheckCheck size={17}/>{draft.status==='reviewed'&&!changed?'Revisado':'Marcar revisado'}</button></div>{draft.status==='reviewed'&&!changed?<button className="text-button draft-reopen" onClick={()=>update('draft')}>Voltar para rascunho</button>:null}<p className="agent-field-hint">Ao editar, a revisão anterior é desfeita. Nenhuma entrega é publicada, enviada ou agendada.</p></>;
}
