'use client';

import {useEffect,useRef,useState} from 'react';
import {ArrowDownLeft,ArrowRight,ArrowUpRight,BarChart3,Building2,Check,CheckCheck,ChevronRight,Clock3,FileText,Home,Layers3,LockKeyhole,LogOut,PanelLeftClose,PanelLeftOpen,Play,Plug,ShieldCheck,Sparkles,Users,Wallet,X} from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import {answerDemo,companies,connections,decisions,initialState} from '@/lib/demo';
import {WhatsAppPreparation} from '@/components/whatsapp-preparation';
import {OrganizationPortfolio} from '@/components/organization-portfolio';
import {useOrganizations,organizationContext} from '@/lib/organizations';
import {LocalBackup} from '@/components/local-backup';
import {CompanyChecklists} from '@/components/company-checklists';
import {BrainStorm} from '@/components/brainstorm';
import {LiveIndicators} from '@/components/live-indicators';
import {AgentHub} from '@/components/agent-hub';
import type {Company,Decision,DecisionStatus,DemoState} from '@/lib/domain';

type View='hoje'|'empresas'|'decisoes'|'agentes'|'perguntar'|'conexoes'|'brainstorm';
const navigation:{id:View;label:string;icon:LucideIcon}[]=[{id:'hoje',label:'Hoje',icon:Home},{id:'empresas',label:'Empresas',icon:Building2},{id:'decisoes',label:'Decisões',icon:CheckCheck},{id:'agentes',label:'Agentes',icon:Layers3},{id:'brainstorm',label:'BrainStorm',icon:FileText},{id:'perguntar',label:'Perguntar à none',icon:Sparkles}];
const statusLabel:Record<DecisionStatus,string>={pending:'Pendente',approved:'Aprovada',deferred:'Adiada',rejected:'Não aprovada'};
const storageKey='none-workspace-v2';
const validStatuses=['pending','approved','deferred','rejected'];
function restoreState():DemoState {
 const raw=localStorage.getItem(storageKey);if(!raw)return initialState;
 const value=JSON.parse(raw) as DemoState;
 if(value.version!==1||!value.decisions||!value.agentRuns||!Array.isArray(value.audit))throw Error('invalid');
 if(!Object.entries(value.decisions).every(([id,r])=>decisions.some(d=>d.id===id)&&r&&validStatuses.includes(r.status)&&typeof r.updatedAt==='string'&&typeof r.note==='string'))throw Error('invalid');
 if(!Object.values(value.agentRuns).every(v=>typeof v==='string')||!value.audit.every(e=>e&&typeof e.id==='string'&&typeof e.at==='string'&&typeof e.note==='string'&&validStatuses.includes(e.status)&&decisions.some(d=>d.id===e.decisionId)))throw Error('invalid');
 return value;
}
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}) {return <span className={`badge ${tone}`}>{children}</span>;}
function CompanyMark({company,small=false}:{company:Company;small?:boolean}) {return <span aria-hidden="true" className={`company-mark ${company.color} ${small?'small':''}`}>{company.initials}</span>;}
function Empty({title,description}:{title:string;description:string}){return <div className="empty"><CheckCheck size={28}/><h3>{title}</h3><p>{description}</p></div>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);
 return <dialog ref={ref} className="modal" aria-labelledby="decision-title" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><span className="eyebrow">NONE / DECISÃO</span><button className="icon-button" onClick={onClose} aria-label="Fechar detalhe"><X size={20}/></button></div><h2 id="decision-title">{title}</h2>{children}</dialog>;
}
export function Cockpit(){
 const portfolio=useOrganizations();
 const [view,setView]=useState<View>('hoje');const [collapsed,setCollapsed]=useState(false);const [state,setState]=useState<DemoState>(initialState);const [ready,setReady]=useState(false);const [toast,setToast]=useState('');const [storageWarning,setStorageWarning]=useState('');const [canSave,setCanSave]=useState(true);
 const [company,setCompany]=useState<Company|null>(null);const [activeDecision,setActiveDecision]=useState<Decision|null>(null);const [note,setNote]=useState('');
 const pending=decisions.filter(d=>(state.decisions[d.id]?.status??'pending')==='pending');
 useEffect(()=>{try{setState(restoreState());}catch{setCanSave(false);setStorageWarning('As alterações anteriores não puderam ser recuperadas. Exibindo o cenário inicial.');}setReady(true);const sync=()=>{const v=location.hash.slice(1);if([...navigation.map(n=>n.id),'conexoes'].includes(v)){setView(v as View);if(v!=='empresas')setCompany(null);}else{setView('hoje');setCompany(null);}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 useEffect(()=>{if(ready&&canSave){try{localStorage.setItem(storageKey,JSON.stringify(state));}catch{setStorageWarning('Este navegador não permite salvar as alterações. Elas durarão apenas nesta sessão.');}}},[state,ready,canSave]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);},[toast]);
 function go(v:View){setView(v);setCompany(null);location.hash=v;window.scrollTo({top:0,behavior:'instant'});}
 function openCompany(c:Company){setCompany(c);setView('empresas');location.hash='empresas';window.scrollTo({top:0,behavior:'instant'});}
 function openDecision(d:Decision){setNote('');setActiveDecision(d);}
 function decide(status:DecisionStatus){if(!activeDecision)return;const at=new Date().toISOString();setState(s=>({...s,decisions:{...s.decisions,[activeDecision.id]:{status,updatedAt:at,note}},audit:[{id:crypto.randomUUID(),decisionId:activeDecision.id,status,at,note},...s.audit].slice(0,200)}));setActiveDecision(null);setToast(`${statusLabel[status]} na demonstração. Nenhuma ação externa foi executada.`);}
 async function logout(){try{const r=await fetch('/api/session',{method:'DELETE'});if(!r.ok)throw Error();window.location.assign('/entrar');}catch{setToast('Não foi possível sair. Tente novamente.');}}
 const title=company?company.short:({hoje:'Hoje',empresas:'Empresas',decisoes:'Decisões',agentes:'Agentes',perguntar:'Perguntar à none',conexoes:'Conexões',brainstorm:'BrainStorm'}[view]);
 return <div className={`shell ${collapsed?'collapsed':''}`}>
  <aside className="sidebar"><div className="brand-row"><button className="brand" onClick={()=>go('hoje')} aria-label="none início">{collapsed?'n.':<>none<span>®</span></>}</button><button className="collapse-button" aria-label={collapsed?'Expandir menu':'Recolher menu'} onClick={()=>setCollapsed(c=>!c)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button></div><div className="workspace-label"><span className="workspace-dot"/>SEU WORKSPACE</div><nav aria-label="Navegação principal">{navigation.map(n=><button key={n.id} title={n.label} aria-label={n.id === 'decisoes' && pending.length > 0 ? n.label + ' ' + pending.length : n.label} aria-current={view===n.id?'page':undefined} className={`nav-item ${view===n.id?'active':''}`} onClick={()=>go(n.id)}><n.icon size={21}/><span>{n.label}</span>{n.id==='decisoes'&&pending.length>0?<b>{pending.length}</b>:null}</button>)}</nav><div className="sidebar-bottom"><div className="private-note"><ShieldCheck size={19}/><div>Seu espaço, privado.<small>Clareza para decidir.</small></div></div><button className={`nav-item ${view==='conexoes'?'active':''}`} onClick={()=>go('conexoes')} title="Conexões"><Plug size={20}/><span>Conexões</span></button><div className="profile"><span className="avatar">V</span><div>Visão do sócio<small>Workspace executivo</small></div><button className="icon-button" title="Sair" aria-label="Sair" onClick={logout}><LogOut size={18}/></button></div></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14}/><strong>{title}</strong></div><div className="topbar-right"><span className="private-label"><LockKeyhole size={13}/>Privado</span><span className="demo-pill">none OS</span><span className="avatar light">V</span><button className="icon-button mobile-control" aria-label="Conexões" onClick={()=>go('conexoes')}><Plug size={18}/></button><button className="icon-button mobile-control" aria-label="Sair" onClick={logout}><LogOut size={18}/></button></div></header>
  <main id="main-content" className="content"><div className="demo-notice"><span className="demo-dot"/><span>Workspace privado · dados salvos neste navegador</span><span className="notice-end">Integrações não conectadas</span></div>{storageWarning?<p role="status" className="storage-warning">{storageWarning}</p>:null}
  <div className="view-transition" key={view+':'+(company?.id??'')} >
  {view==='hoje'&&<><div className="page-heading"><div><p className="eyebrow">NONE / HOLDING DE INVESTIMENTOS</p><h1>Seu portfólio, em perspectiva.</h1><p>Cadastros e notas são seus. Indicadores serão exibidos quando houver fontes conectadas.</p></div></div><div className="overview-stats"><button className="stat-card" onClick={()=>go('empresas')}><span className="stat-label">Investimentos cadastrados</span><strong>{portfolio.items.length}</strong><span className="stat-foot">Organizar portfólio<ArrowUpRight size={17}/></span></button><section className="stat-card"><span className="stat-label">Indicadores financeiros</span><strong>—</strong><span className="stat-foot">Nenhuma fonte conectada</span></section></div><section className="portfolio-section"><div className="section-header"><h2>Investimentos da none</h2><button className="text-button" onClick={()=>go('empresas')}>Gerenciar organizações</button></div><div className="mini-companies">{portfolio.items.map(c=><button key={c.id} onClick={()=>go('empresas')}>{c.logo?<img src={c.logo} alt="" style={{width:32,height:32,objectFit:'contain'}}/>:<Building2 size={22}/>}<span>{c.name}<small>{c.status}</small></span></button>)}</div></section><CompanyChecklists/><section className="panel integration-note"><ShieldCheck size={24}/><div><h3>Seu workspace está pronto para organizar informações.</h3><p>Cadastre os investimentos, registre notas e configure os agentes. IA, WhatsApp, financeiro e agenda aguardam conexão. Nenhum resultado foi presumido.</p></div></section></>}
  {view==='empresas'&&(company?<CompanyDetail company={company} state={state} onBack={()=>setCompany(null)} onDecision={openDecision}/>:<OrganizationPortfolio onLegacy={id=>{const c=companies.find(c=>c.id===id);if(c)openCompany(c);}}/>)}
  {view==='decisoes'&&<Decisions state={state} onOpen={openDecision}/>}
  {view==='agentes'&&<AgentHub state={state} onRun={(id)=>{setState(s=>({...s,agentRuns:{...s.agentRuns,[id]:new Date().toISOString()}}));setToast('Rascunho demonstrativo preparado. Nenhuma ação externa executada.');}}/>}
  {view==='brainstorm'&&<BrainStorm/>}
  {view==='perguntar'&&<Chat state={state}/>}
  {view==='conexoes'&&<><div className="page-heading"><div><p className="eyebrow">SEUS SISTEMAS, CONECTADOS</p><h1>O contexto começa nas fontes.</h1><p>A none reúne informação acima dos seus sistemas existentes.</p></div></div><div className="integration-note"><ShieldCheck size={24}/><div><h3>Uma camada executiva para o seu ecossistema.</h3><p>ERP e CRM continuam sendo as fontes da operação. Nenhuma integração está ativa.</p></div></div><LocalBackup/><WhatsAppPreparation/><div className="connection-grid">{connections.map(c=><section className="panel connector" key={c.name}><div><span className="stat-icon"><Plug size={22}/></span><Badge>Não conectado</Badge></div><h2>{c.name}</h2><p>{c.purpose}</p><small>{c.kind}</small><div className="connector-footer">Integração prevista para a próxima etapa</div></section>)}</div></>}
  </div><footer className="page-footer"><span className="footer-brand">none.</span><span>Holding de investimentos · Workspace privado</span><span>Dados locais</span></footer></main></div>
  {toast?<div className="toast" role="status"><Check size={18}/>{toast}<button aria-label="Fechar aviso" onClick={()=>setToast('')}><X size={16}/></button></div>:null}
  {activeDecision?<Modal title={activeDecision.title} onClose={()=>setActiveDecision(null)}><div className="modal-meta"><Badge tone="green">{companies.find(c=>c.id===activeDecision.companyId)!.short}</Badge><Badge tone={activeDecision.priority==='Alta'?'amber':'neutral'}>Prioridade {activeDecision.priority.toLowerCase()}</Badge><Badge>{statusLabel[state.decisions[activeDecision.id]?.status??'pending']}</Badge></div><div className="modal-section"><h3>Contexto</h3><p>{activeDecision.context}</p></div><div className="recommendation"><Sparkles size={21}/><div><h3>Sugestão da none</h3><p>{activeDecision.recommendation}</p></div></div><div className="modal-section"><h3>Impacto e limites</h3><p>{activeDecision.impact}</p></div><label className="field-label" htmlFor="decision-note">Sua observação <span>(opcional)</span></label><textarea id="decision-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={600} placeholder="Registre o contexto da sua decisão…"/><p className="source-note">Fonte: cenário fictício · 24 set 2026. A decisão fica salva neste navegador.</p><div className="decision-actions"><button className="text-button danger" onClick={()=>decide('rejected')}>Não aprovar</button><button className="outline" onClick={()=>decide('deferred')}><Clock3 size={16}/>Adiar</button><button className="primary" onClick={()=>decide('approved')}><Check size={16}/>Aprovar</button></div>{(state.decisions[activeDecision.id]?.status??'pending')!=='pending'?<button className="text-button reopen" onClick={()=>decide('pending')}>Reabrir decisão</button>:null}</Modal>:null}
 </div>;
}

function DecisionRow({decision:d,onClick,status}:{decision:Decision;onClick:()=>void;status?:DecisionStatus}){const c=companies.find(c=>c.id===d.companyId)!;return <button className="decision-row" onClick={onClick}><CompanyMark company={c} small/><div className="decision-copy"><small>{c.short}</small><h3>{d.title}</h3><p>{d.summary}</p></div><div className="decision-tail"><Badge tone={status&&status!=='pending'?'green':d.priority==='Alta'?'amber':'neutral'}>{status&&status!=='pending'?statusLabel[status]:d.priority}</Badge><small>{status&&status!=='pending'?'Registrada':d.due}</small></div><ChevronRight className="row-arrow" size={17}/></button>;}

function Companies({onSelect}:{onSelect:(c:Company)=>void}){const [filter,setFilter]=useState('Todas');const filtered=companies.filter(c=>filter==='Todas'||(filter==='Em operação'?c.type==='operacao':c.type==='implantacao'));return <><div className="page-heading"><div><p className="eyebrow">UMA VISÃO DO TODO</p><h1>Seu portfólio, conectado.</h1><p>Seis empresas. Diferentes momentos. Um só espaço de decisão.</p></div><span className="count-label">06 empresas</span></div><div className="filter-row" aria-label="Filtrar empresas">{['Todas','Em operação','Em implantação'].map(f=><button key={f} className={filter===f?'selected':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}<span>{f==='Todas'?6:f==='Em operação'?4:2}</span></button>)}</div><div className="company-grid">{filtered.map(c=><button className="company-card" key={c.id} onClick={()=>onSelect(c)}><div className="company-card-top"><CompanyMark company={c}/><Badge tone={c.type==='implantacao'?'amber':'green'}>{c.type==='implantacao'?'Em implantação':'Em operação'}</Badge></div><h2>{c.name}</h2><p className="sector">{c.sector}</p><p>{c.description}</p><div className="company-card-bottom"><span>{c.type==='implantacao'?'Acompanhar investimento':'Abrir visão executiva'}</span><ArrowUpRight size={20}/></div></button>)}</div></>;}

// Companies with a read-only Supabase summary (see src/lib/indicators.ts); null shows every group.
const liveCompanies=['integral','mcl','reurb'];
const liveGroups:Record<string,string[]|null>={Financeiro:['Financeiro'],Clientes:['Clientes','Comercial'],Indicadores:null};

function CompanyDetail({company:c,state,onBack,onDecision}:{company:Company;state:DemoState;onBack:()=>void;onDecision:(d:Decision)=>void}){const [tab,setTab]=useState('Visão geral');const tabs=['Visão geral','Financeiro','Clientes','Documentos','Decisões','Indicadores'];const related=decisions.filter(d=>d.companyId===c.id);const live=liveCompanies.includes(c.id);const liveTab=live&&tab in liveGroups;return <><button className="text-button back-button" onClick={onBack}><ArrowDownLeft size={16}/>Todas as empresas</button><div className="company-detail-heading"><CompanyMark company={c}/><div><p className="eyebrow">{c.sector}</p><h1>{c.name}</h1></div><Badge tone={c.type==='implantacao'?'amber':'green'}>{c.type==='implantacao'?'Em implantação':'Em operação'}</Badge></div><p className="detail-description">{c.description}</p><div className="tabs" role="tablist" aria-label="Áreas da empresa">{tabs.map(t=><button key={t} id={`tab-${t}`} role="tab" aria-selected={tab===t} aria-controls="company-tabpanel" className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}</button>)}</div><section id="company-tabpanel" role="tabpanel" aria-labelledby={`tab-${tab}`}>
 {tab==='Visão geral'?<>{live?<LiveIndicators companyId={c.id}/>:<div className="metrics-grid">{c.metrics.map(m=><div className="panel metric" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small>{m.note}</small></div>)}</div>}<div className="detail-grid"><section className="panel next-step"><p className="eyebrow">PRÓXIMO PASSO SUGERIDO</p><h2>{c.nextStep}</h2><p>{c.type==='implantacao'?'Estrutura extensível para acompanhar aportes, clientes, documentos e marcos do investimento.':'Os indicadores dependem da conexão com os sistemas de origem.'}</p><Badge>Fontes pendentes</Badge></section><section className="panel"><div className="section-header"><h2>Decisões da empresa</h2></div>{related.length?related.map(d=><DecisionRow key={d.id} decision={d} onClick={()=>onDecision(d)} status={state.decisions[d.id]?.status}/>):<Empty title="Nenhuma decisão cadastrada" description="Este espaço reunirá as decisões que precisam do seu olhar."/>}</section></div></>:null}
 {tab==='Decisões'?<section className="panel">{related.length?related.map(d=><DecisionRow key={d.id} decision={d} onClick={()=>onDecision(d)} status={state.decisions[d.id]?.status}/>):<Empty title="Nenhuma decisão por aqui" description="A estrutura está pronta para decisões futuras desta empresa."/>}</section>:null}
 {liveTab?<LiveIndicators companyId={c.id} groups={liveGroups[tab]??undefined}/>:null}
 {tab!=='Visão geral'&&tab!=='Decisões'&&!liveTab?<section className="panel planned-area"><div className="planned-icon">{tab==='Financeiro'?<Wallet size={28}/>:tab==='Clientes'?<Users size={28}/>:tab==='Documentos'?<FileText size={28}/>:<BarChart3 size={28}/>}</div><Badge>Estrutura preparada</Badge><h2>{tab==='Financeiro'?'Uma visão financeira, com contexto.':tab==='Clientes'?'Relacionamento que vira informação.':tab==='Documentos'?'Os documentos por trás das decisões.':'Indicadores para acompanhar a evolução.'}</h2><p>{c.id==='ct'?'O CT Diego Silva está preparado para receber relatórios financeiros e de clientes. ':c.type==='implantacao'?'Este investimento está em implantação. ':''}Nenhuma fonte real foi conectada. Os relatórios aparecerão aqui após a integração.</p><div className="planned-fields">{(tab==='Financeiro'?['Receitas e despesas','Resultado por período','Fluxo de caixa',...(c.type==='implantacao'?['Aportes e investimentos']:[])]:tab==='Clientes'?['Base de clientes','Recorrência e retenção','Evolução por período']:tab==='Documentos'?['Contratos','Documentos da empresa','Anexos de decisões']:['Indicador e definição','Meta e evolução','Fonte e atualização']).map(x=><span key={x}><Check size={15}/>{x}</span>)}</div><small>Sem números reais ou projeções inventadas.</small></section>:null}
 </section></>;}

function Decisions({state,onOpen}:{state:DemoState;onOpen:(d:Decision)=>void}){const [filter,setFilter]=useState('pending');const [companyId,setCompanyId]=useState('all');const list=decisions.filter(d=>(companyId==='all'||d.companyId===companyId)&&(filter==='all'||(state.decisions[d.id]?.status??'pending')===filter));return <><div className="page-heading"><div><p className="eyebrow">DO CONTEXTO À AÇÃO</p><h1>As decisões passam por você.</h1><p>Avalie o contexto, registre sua escolha e acompanhe o histórico.</p></div></div><div className="decision-filters"><div className="filter-row">{[['pending','Pendentes'],['approved','Aprovadas'],['deferred','Adiadas'],['all','Todas']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><select aria-label="Filtrar decisões por empresa" value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="all">Todas as empresas</option>{companies.map(c=><option key={c.id} value={c.id}>{c.short}</option>)}</select></div><section className="panel">{list.length?list.map(d=><DecisionRow decision={d} key={d.id} status={state.decisions[d.id]?.status} onClick={()=>onOpen(d)}/>):<Empty title="Nenhuma decisão neste filtro" description="Escolha outro status ou outra empresa para continuar."/>}</section><section className="panel history"><div className="section-header"><h2>Histórico de decisões</h2><Badge>Salvo neste navegador</Badge></div>{state.audit.length?state.audit.map(a=><div className="history-row" key={a.id}><span className="history-check"><Check size={16}/></span><div><h3>{decisions.find(d=>d.id===a.decisionId)?.title}</h3><p>{statusLabel[a.status]} · {new Date(a.at).toLocaleString('pt-BR')}</p>{a.note?<blockquote>{a.note}</blockquote>:null}</div><Badge>Simulação</Badge></div>):<p className="history-empty">Suas escolhas aparecerão aqui. Nenhuma decisão registrada ainda.</p>}</section></>;}

function Chat({state}:{state:DemoState}){const portfolio=useOrganizations();const [question,setQuestion]=useState('');const [companyId,setCompanyId]=useState('all');const [messages,setMessages]=useState<{role:'user'|'assistant';text:string}[]>([]);const [busy,setBusy]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const bottom=useRef<HTMLDivElement>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);useEffect(()=>{const panel=bottom.current?.parentElement;if(messages.length&&panel)panel.scrollTo({top:panel.scrollHeight,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[messages]);function ask(q:string){if(!q.trim()||busy)return;setMessages(m=>[...m,{role:'user',text:q.trim()}]);setQuestion('');setBusy(true);timer.current=setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',text:organizationContext(companyId)+'\n\nDisponibilidade da IA:\n'+answerDemo()}]);setBusy(false);},550);}return <><div className="page-heading chat-heading"><div><p className="eyebrow">CONVERSE COM O SEU CONTEXTO</p><h1>Perguntar à none</h1><p>Uma pergunta. Uma visão mais clara.</p></div><Badge>Consulta ao cadastro</Badge></div><section className="chat-panel"><div className="chat-toolbar"><span><Sparkles size={18}/>none Executive</span><select aria-label="Contexto da conversa" value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="all">Todo o portfólio</option>{portfolio.items.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></div><div className="chat-messages" role="log" aria-label="Conversa com none" aria-live="polite">{messages.length===0?<div className="chat-welcome"><div className="none-orb">n.</div><h2>Por onde começamos?</h2><p>Explore as prioridades e o contexto das suas empresas.</p><div className="suggestions">{['Mostrar contexto cadastrado','Consultar investimentos','Consultar informações das empresas'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={17}/></button>)}</div></div>:messages.map((m,i)=><div className={`message ${m.role}`} key={i}>{m.role==='assistant'?<span className="message-avatar">n.</span>:null}<div><small>{m.role==='assistant'?'none · cadastro':'Você'}</small><p>{m.text}</p></div></div>)}{busy?<div role="status" className="thinking">Consultando cadastro…</div>:null}<div ref={bottom}/></div><form className="chat-form" onSubmit={e=>{e.preventDefault();ask(question);}}><label className="sr-only" htmlFor="question">Sua pergunta para a none</label><input id="question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} placeholder="Pergunte sobre suas empresas…" autoComplete="off"/><button className="send-button" aria-label="Enviar pergunta" disabled={!question.trim()||busy}><ArrowRight size={21}/></button></form><p className="chat-disclaimer">Consulta ao cadastro local. IA e fontes externas ainda não conectadas.</p></section></>;}

