'use client';
import {useEffect,useState} from 'react';
import {useOrganizations,organizationContext} from '@/lib/organizations';
import {Plus,Sparkles,Pencil,Archive,LayoutGrid,CalendarDays,ChevronLeft,ChevronRight,CheckSquare} from 'lucide-react';
type Item={id:string;company:string;title:string;frequency:'weekly'|'monthly';completed:string[];archived:boolean};
const key='none-checklists-v1';
function localDate(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
export function periodKey(date:Date,frequency:'weekly'|'monthly'){if(frequency==='monthly')return localDate(date).slice(0,7);const monday=new Date(date.getFullYear(),date.getMonth(),date.getDate());monday.setDate(monday.getDate()-(monday.getDay()+6)%7);return localDate(monday);}
export function CompanyChecklists(){const orgs=useOrganizations();const [items,setItems]=useState<Item[]>([]);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [company,setCompany]=useState('integral');const [frequency,setFrequency]=useState<'weekly'|'monthly'>('weekly');const [date,setDate]=useState(()=>localDate(new Date()));const [title,setTitle]=useState('');const [edit,setEdit]=useState<string|null>(null);const [help,setHelp]=useState(false);const [showArchive,setShowArchive]=useState(false);const [view,setView]=useState<'grid'|'calendar'>('grid');const [adding,setAdding]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const v=JSON.parse(raw);if(v.version!==1||!Array.isArray(v.items)||!v.items.every((i:Item)=>i&&typeof i.id==='string'&&typeof i.company==='string'&&typeof i.title==='string'&&['weekly','monthly'].includes(i.frequency)&&Array.isArray(i.completed)&&i.completed.every(x=>typeof x==='string')&&typeof i.archived==='boolean'))throw Error();setItems(v.items);}setReady(true);}catch{setNotice('Não foi possível recuperar os checklists. O conteúdo salvo foi preservado.');}},[]);
 function commit(next:Item[]){try{localStorage.setItem(key,JSON.stringify({version:1,items:next}));setItems(next);setNotice('Checklist salvo neste navegador.');return true;}catch{setNotice('Não foi possível salvar. A alteração não foi aplicada.');return false;}}
 const cycle=periodKey(new Date((date||localDate(new Date()))+'T12:00:00'),frequency);const list=items.filter(i=>i.company===company&&i.frequency===frequency&&i.archived===showArchive);const count=list.filter(i=>i.completed.includes(cycle)).length;
 function add(e:React.FormEvent){e.preventDefault();if(!title.trim()||!ready)return;const next=edit?items.map(i=>i.id===edit?{...i,title:title.trim()}:i):[...items,{id:crypto.randomUUID(),company,title:title.trim(),frequency,completed:[],archived:false}];if(commit(next)){setTitle('');setEdit(null);setAdding(false);}}
 const selectedDate=new Date((date||localDate(new Date()))+'T12:00:00');const monthStart=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);const offset=(monthStart.getDay()+6)%7;const days=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,0).getDate();
 function moveMonth(delta:number){setDate(localDate(new Date(selectedDate.getFullYear(),selectedDate.getMonth()+delta,1)));}
 return <section className="panel company-checklists simple-checks" aria-label="Checklists por empresa"><div className="section-header"><div><p className="eyebrow">SUA ROTINA</p><h2>Um passo de cada vez.</h2></div><button className="icon-button" aria-label="Apoio da none" onClick={()=>setHelp(!help)} aria-expanded={help}><Sparkles size={20}/></button></div>
 <div className="check-view-tabs"><button aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={16}/>Checklist</button><button aria-pressed={view==='calendar'} onClick={()=>setView('calendar')}><CalendarDays size={16}/>Calendário</button></div>
 <div className="check-simple-filters"><select aria-label="Investimento do checklist" value={company} onChange={e=>{setCompany(e.target.value);setEdit(null);setAdding(false);setTitle('');}}>{orgs.items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><div className="check-period-tabs">{(['weekly','monthly'] as const).map(f=><button key={f} aria-pressed={frequency===f} onClick={()=>{setFrequency(f);setEdit(null);setAdding(false);setTitle('');}}>{f==='weekly'?'Semana':'Mês'}</button>)}</div></div>
 {view==='calendar'&&<div className="check-calendar"><div className="check-month-nav"><button className="icon-button" aria-label="Mês anterior" onClick={()=>moveMonth(-1)}><ChevronLeft size={18}/></button><strong>{selectedDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button className="icon-button" aria-label="Próximo mês" onClick={()=>moveMonth(1)}><ChevronRight size={18}/></button></div><div className="check-month-grid">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><small key={d}>{d}</small>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),i+1);const dateKey=localDate(d);const periodStart=frequency==='weekly'?d.getDay()===1:i===0;const total=items.filter(x=>x.company===company&&!x.archived&&x.frequency===frequency).length;return <button key={dateKey} aria-label={'Selecionar '+d.toLocaleDateString('pt-BR')} aria-pressed={date===dateKey} onClick={()=>setDate(dateKey)}>{i+1}{periodStart&&total>0&&<span className="check-day-dot"/>}</button>;})}</div><p className="check-hint">Selecione um dia para consultar o período. Os pontos indicam o início de cada checklist; não são compromissos agendados.</p><details className="check-connections"><summary>Conectar calendários</summary><p><strong>Google Agenda</strong> · Não conectado</p><p><strong>Calendário da empresa</strong> · Sistema a definir</p><p>A sincronização depende de autorização e da integração com cada serviço. Nenhum evento externo foi importado ou criado.</p></details></div>}
 <div className="check-list-heading"><span>{frequency==='weekly'?'Semana de '+new Date(cycle+'T12:00:00').toLocaleDateString('pt-BR'):selectedDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} · {count}/{list.length}</span><button className="text-button" onClick={()=>{setAdding(!adding);setEdit(null);setTitle('');}}><Plus size={17}/>Novo item</button></div>
 {adding&&<form className="check-add" onSubmit={add}><label className="sr-only" htmlFor="check-title">Pendência do checklist</label><input autoFocus id="check-title" value={title} maxLength={240} onChange={e=>setTitle(e.target.value)} placeholder="O que precisa ser feito?" required/><button className="primary" disabled={!ready||!orgs.ready||!title.trim()}>{edit?'Salvar':'Adicionar'}</button><button type="button" className="text-button" onClick={()=>{setAdding(false);setEdit(null);}}>Cancelar</button></form>}
 <div className="check-card-grid">{list.map(i=><article className="check-task-card" key={i.id}><span className="check-task-icon"><CheckSquare size={20}/></span><label><span className={i.completed.includes(cycle)?'done':''}>{i.title}</span><small>{i.frequency==='weekly'?'Toda semana':'Todo mês'}</small><input type="checkbox" disabled={!ready||showArchive} checked={i.completed.includes(cycle)} onChange={e=>commit(items.map(x=>x.id===i.id?{...x,completed:e.target.checked?[...x.completed,cycle]:x.completed.filter(c=>c!==cycle)}:x))}/></label><div className="check-card-tools"><button className="icon-button" aria-label={'Editar '+i.title} onClick={()=>{setEdit(i.id);setTitle(i.title);setAdding(true);}}><Pencil size={13}/></button><button className="icon-button" aria-label={(showArchive?'Restaurar ':'Arquivar ')+i.title} onClick={()=>commit(items.map(x=>x.id===i.id?{...x,archived:!x.archived}:x))}><Archive size={13}/></button></div></article>)}</div>
 {!list.length&&<div className="check-empty"><CheckSquare size={26}/><p>{showArchive?'Nenhum item arquivado.':'Seu checklist começa com um próximo passo.'}</p><small>Adicione os itens que se repetem nesta empresa.</small></div>}
 <div className="check-bottom"><button className="text-button" onClick={()=>setShowArchive(!showArchive)}>{showArchive?'Ver ativos':'Arquivados'}</button><span>Conclusão por período · salvo neste navegador</span></div>
 {help&&<aside className="check-help"><h3>Apoio da none</h3><p>IA não conectada. Contexto e pendências preparados para a futura integração.</p><pre>{organizationContext(company)+'\n\nPENDÊNCIAS\n'+list.filter(i=>!i.completed.includes(cycle)).map(i=>'☐ '+i.title).join('\n')}</pre></aside>}<p role="status" className="check-hint">{notice}</p></section>;
}
