'use client';
import {useEffect,useState} from 'react';
import {useOrganizations,organizationContext} from '@/lib/organizations';
import {checklistIcons,checklistIcon,companyColor} from '@/lib/brand';
import {Plus,Sparkles,Pencil,Archive,LayoutGrid,CalendarDays,CalendarPlus,ChevronLeft,ChevronRight,CheckSquare} from 'lucide-react';
import {useGoogleEvents,eventDays,scheduleOnGoogle,GoogleConnection,EventRow} from '@/components/google-agenda';
type Item={id:string;company:string;title:string;frequency:'weekly'|'monthly';completed:string[];archived:boolean;icon?:string};
const key='none-checklists-v1';
function localDate(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
export function periodKey(date:Date,frequency:'weekly'|'monthly'){if(frequency==='monthly')return localDate(date).slice(0,7);const monday=new Date(date.getFullYear(),date.getMonth(),date.getDate());monday.setDate(monday.getDate()-(monday.getDay()+6)%7);return localDate(monday);}
export function CompanyChecklists(){const orgs=useOrganizations();const [items,setItems]=useState<Item[]>([]);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [company,setCompany]=useState('all');const [frequency,setFrequency]=useState<'weekly'|'monthly'>('weekly');const [date,setDate]=useState(()=>localDate(new Date()));const [title,setTitle]=useState('');const [icon,setIcon]=useState('check');const [target,setTarget]=useState('');const [edit,setEdit]=useState<string|null>(null);const [help,setHelp]=useState(false);const [showArchive,setShowArchive]=useState(false);const [view,setView]=useState<'grid'|'calendar'>('grid');const [adding,setAdding]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const v=JSON.parse(raw);if(v.version!==1||!Array.isArray(v.items)||!v.items.every((i:Item)=>i&&typeof i.id==='string'&&typeof i.company==='string'&&typeof i.title==='string'&&['weekly','monthly'].includes(i.frequency)&&Array.isArray(i.completed)&&i.completed.every(x=>typeof x==='string')&&typeof i.archived==='boolean'&&(i.icon===undefined||typeof i.icon==='string')))throw Error();setItems(v.items);}setReady(true);}catch{setNotice('Não foi possível recuperar os checklists. O conteúdo salvo foi preservado.');}},[]);
 function commit(next:Item[]){try{localStorage.setItem(key,JSON.stringify({version:1,items:next}));setItems(next);setNotice('Checklist salvo neste navegador.');return true;}catch{setNotice('Não foi possível salvar. A alteração não foi aplicada.');return false;}}
 const all=company==='all';const orgOf=(id:string)=>orgs.items.find(o=>o.id===id);
 const cycle=periodKey(new Date((date||localDate(new Date()))+'T12:00:00'),frequency);const list=items.filter(i=>(all||i.company===company)&&i.frequency===frequency&&i.archived===showArchive).sort((a,b)=>all?(orgs.items.findIndex(o=>o.id===a.company)-orgs.items.findIndex(o=>o.id===b.company)):0);const count=list.filter(i=>i.completed.includes(cycle)).length;
 function reset(){setTitle('');setIcon('check');setEdit(null);setAdding(false);}
 function open(item?:Item){setAdding(true);setEdit(item?.id??null);setTitle(item?.title??'');setIcon(item?.icon??'check');setTarget(item?.company??(all?orgs.items[0]?.id??'':company));}
 function add(e:React.FormEvent){e.preventDefault();const owner=all||edit?target:company;if(!title.trim()||!ready||!orgOf(owner))return;const next=edit?items.map(i=>i.id===edit?{...i,title:title.trim(),icon,company:owner}:i):[...items,{id:crypto.randomUUID(),company:owner,title:title.trim(),frequency,completed:[],archived:false,icon}];if(commit(next))reset();}
 const selectedDate=new Date((date||localDate(new Date()))+'T12:00:00');const monthStart=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);const offset=(monthStart.getDay()+6)%7;const days=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,0).getDate();
 const gcal=useGoogleEvents(monthStart,new Date(selectedDate.getFullYear(),selectedDate.getMonth()+1,1));const busyDays=new Set(gcal.events.flatMap(eventDays));const dayEvents=gcal.events.filter(e=>eventDays(e).includes(date));
 async function schedule(i:Item){try{await scheduleOnGoogle(i.title,date);setNotice('Agendado no Google Agenda em '+selectedDate.toLocaleDateString('pt-BR')+'.');gcal.reload();}catch(e){setNotice((e as Error).message);}}
 function moveMonth(delta:number){setDate(localDate(new Date(selectedDate.getFullYear(),selectedDate.getMonth()+delta,1)));}
 const pickColor=companyColor(orgOf(all||edit?target:company));
 return <section className="panel company-checklists simple-checks" aria-label="Checklists por empresa"><div className="section-header"><div><p className="eyebrow">SUA ROTINA</p><h2>Um passo de cada vez.</h2></div><button className="icon-button" aria-label="Apoio da none" onClick={()=>setHelp(!help)} aria-expanded={help}><Sparkles size={20}/></button></div>
 <div className="check-view-tabs"><button aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={16}/>Checklist</button><button aria-pressed={view==='calendar'} onClick={()=>setView('calendar')}><CalendarDays size={16}/>Calendário</button></div>
 <div className="check-simple-filters"><select aria-label="Investimento do checklist" value={company} onChange={e=>{setCompany(e.target.value);reset();}}><option value="all">Todas as empresas</option>{orgs.items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><div className="check-period-tabs">{(['weekly','monthly'] as const).map(f=><button key={f} aria-pressed={frequency===f} onClick={()=>{setFrequency(f);reset();}}>{f==='weekly'?'Semana':'Mês'}</button>)}</div></div>
 {view==='calendar'&&<div className="check-calendar"><div className="check-month-nav"><button className="icon-button" aria-label="Mês anterior" onClick={()=>moveMonth(-1)}><ChevronLeft size={18}/></button><strong>{selectedDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button className="icon-button" aria-label="Próximo mês" onClick={()=>moveMonth(1)}><ChevronRight size={18}/></button></div><div className="check-month-grid">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><small key={d}>{d}</small>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const d=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),i+1);const dateKey=localDate(d);const periodStart=frequency==='weekly'?d.getDay()===1:i===0;const total=items.filter(x=>(all||x.company===company)&&!x.archived&&x.frequency===frequency).length;return <button key={dateKey} aria-label={'Selecionar '+d.toLocaleDateString('pt-BR')} aria-pressed={date===dateKey} onClick={()=>setDate(dateKey)}>{i+1}{periodStart&&total>0&&<span className="check-day-dot"/>}{busyDays.has(dateKey)&&<span className="gcal-day-dot" aria-label="Tem compromisso"/>}</button>;})}</div><p className="check-hint"><span className="legend-dot"/>início do checklist <span className="legend-dot gcal"/>compromisso no Google Agenda</p>{gcal.state==='ok'&&<div className="gcal-day-list"><h3>{selectedDate.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</h3>{dayEvents.length?dayEvents.map(e=><EventRow key={e.id} e={e}/>):<p className="agenda-empty">Nenhum compromisso neste dia.</p>}</div>}<GoogleConnection state={gcal.state} onChange={gcal.reload}/></div>}
 <div className="check-list-heading"><span>{frequency==='weekly'?'Semana de '+new Date(cycle+'T12:00:00').toLocaleDateString('pt-BR'):selectedDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} · {count}/{list.length}{all&&' · todas as empresas'}</span><button className="text-button" onClick={()=>adding?reset():open()}><Plus size={17}/>Novo item</button></div>
 {adding&&<form className="check-add check-add-rich" onSubmit={add}><div className="check-add-row">{(all||edit)&&<select aria-label="Empresa do item" value={target} onChange={e=>setTarget(e.target.value)}>{orgs.items.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>}<label className="sr-only" htmlFor="check-title">Pendência do checklist</label><input autoFocus id="check-title" value={title} maxLength={240} onChange={e=>setTitle(e.target.value)} placeholder="O que precisa ser feito?" required/></div>
  <fieldset className="icon-picker" style={{'--pick':pickColor} as React.CSSProperties}><legend>Ícone</legend><div className="icon-grid">{checklistIcons.map(({key:k,label,Icon})=><button type="button" key={k} aria-label={label} title={label} aria-pressed={icon===k} onClick={()=>setIcon(k)}><Icon size={18}/></button>)}</div></fieldset>
  <div className="check-add-actions"><button className="primary" disabled={!ready||!orgs.ready||!title.trim()}>{edit?'Salvar':'Adicionar'}</button><button type="button" className="text-button" onClick={reset}>Cancelar</button></div></form>}
 <div className="check-card-grid">{list.map(i=>{const org=orgOf(i.company);const color=companyColor(org);const Icon=checklistIcon(i.icon);return <article className="check-task-card" key={i.id}><span className="check-task-icon" style={{color,background:color+'1f'}}><Icon size={20}/></span><label><span className={i.completed.includes(cycle)?'done':''}>{i.title}</span><small>{all&&<b style={{color}}>{org?.name??'Empresa removida'} · </b>}{i.frequency==='weekly'?'Toda semana':'Todo mês'}</small><input type="checkbox" disabled={!ready||showArchive} checked={i.completed.includes(cycle)} onChange={e=>commit(items.map(x=>x.id===i.id?{...x,completed:e.target.checked?[...x.completed,cycle]:x.completed.filter(c=>c!==cycle)}:x))}/></label><div className="check-card-tools">{gcal.state==='ok'&&!showArchive&&<button className="icon-button" aria-label={'Agendar '+i.title+' no Google Agenda em '+selectedDate.toLocaleDateString('pt-BR')} title={'Agendar no Google Agenda em '+selectedDate.toLocaleDateString('pt-BR')} onClick={()=>schedule(i)}><CalendarPlus size={13}/></button>}<button className="icon-button" aria-label={'Editar '+i.title} onClick={()=>open(i)}><Pencil size={13}/></button><button className="icon-button" aria-label={(showArchive?'Restaurar ':'Arquivar ')+i.title} onClick={()=>commit(items.map(x=>x.id===i.id?{...x,archived:!x.archived}:x))}><Archive size={13}/></button></div></article>;})}</div>
 {!list.length&&<div className="check-empty"><CheckSquare size={26}/><p>{showArchive?'Nenhum item arquivado.':'Seu checklist começa com um próximo passo.'}</p><small>{all?'Adicione itens e escolha a empresa de cada um.':'Adicione os itens que se repetem nesta empresa.'}</small></div>}
 <div className="check-bottom"><button className="text-button" onClick={()=>setShowArchive(!showArchive)}>{showArchive?'Ver ativos':'Arquivados'}</button><span>Conclusão por período · salvo neste navegador</span></div>
 {help&&<aside className="check-help"><h3>Apoio da none</h3><p>IA não conectada. Contexto e pendências preparados para a futura integração.</p><pre>{organizationContext(company)+'\n\nPENDÊNCIAS\n'+list.filter(i=>!i.completed.includes(cycle)).map(i=>'☐ '+(all?(orgOf(i.company)?.name??'')+' · ':'')+i.title).join('\n')}</pre></aside>}<p role="status" className="check-hint">{notice}</p></section>;
}
